name: Build PathfinderWOTR-IsekaiMod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup .NET Framework
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet Packages
      run: nuget restore IsekaiMod/IsekaiMod.sln || echo "NuGet restore failed"

    - name: Build Mod DLL
      run: |
        msbuild IsekaiMod/IsekaiMod.sln /p:Configuration=Release || echo "Build failed"

    - name: Verify Build Output
      run: |
        if (!(Test-Path "IsekaiMod/bin/Release/IsekaiMod.dll")) {
          Write-Host "❌ Build failed: DLL not found!"
          exit 1
        } else {
          Write-Host "✅ Build succeeded: DLL found."
        }

    - name: Upload Compiled DLL
      uses: actions/upload-artifact@v3
      with:
        name: Compiled-DLL
        path: IsekaiMod/bin/Release/*.dll
